### ISSUE TITLE
Add annotations for some userful things

### ISSUE THREAD

**Issue by joehoyle** [humanmade/aws-xray#10]
X-Ray annotations are data on a trace than can be searched for across all traces, essentially as indexed information. We may want to add some data to annotations to we can find traces by custom data, such as:

- user ID
- Error message
- MySQL queries
- WP CLI comands (when we start tracking those)
- front-end / backend
- batcache HITs
- Country

etc

**Comment by rmccue** [comment]
@joehoyle can you clarify what you were intending with this issue? Otherwise, will close.

**Comment by joehoyle** [comment]
@rmccue I fleshed out the description.

**Comment by veselala** [comment]
Added as a "New idea" on Productboard https://altis.productboard.com/feature-board/2242997-product-features/features/6455582/detail
