### ISSUE TITLE
Large payloads cause PHP Warnings

### ISSUE THREAD

**Issue by joehoyle** [humanmade/aws-xray#14]
Hey folks, minor issue that relates more to the stack than our site, but figured I'd report anyways. I'm seeing quite a few instances in New Relic of `socket_sendto(): unable to write to socket [90]: Message too long` popping up from various points in the application. Seems to have something to do with X-Ray; I haven't encountered any specific issues in the admin interface relating to this, but wanted to report anyway since it's originating from multiple points in the application.

A stack trace for example:
```
E_WARNING: socket_sendto(): unable to write to socket [90]: Message too long
in socket_sendto called at /srv/www/release-aca3a7ebed71330bc9403ee2806a5fca-1527259168/wp-content/hm-platform/plugins/aws-xray/plugin.php (130)
in HM\Platform\XRay\send_trace_to_daemon called at /srv/www/release-aca3a7ebed71330bc9403ee2806a5fca-1527259168/wp-content/hm-platform/plugins/aws-xray/plugin.php (99)
in HM\Platform\XRay\trace_wpdb_query called at /srv/www/release-aca3a7ebed71330bc9403ee2806a5fca-1527259168/wp-content/hm-platform/plugins/aws-xray/inc/class-db.php (12)
in HM\Platform\XRay\DB::query called at /srv/www/release-aca3a7ebed71330bc9403ee2806a5fca-1527259168/wordpress/wp-includes/wp-db.php (2166)
in wpdb::update called at /srv/www/release-aca3a7ebed71330bc9403ee2806a5fca-1527259168/wordpress/wp-includes/post.php (3372)
in wp_insert_post called at /srv/www/release-aca3a7ebed71330bc9403ee2806a5fca-1527259168/wordpress/wp-includes/post.php (3654)
in wp_update_post called at /srv/www/release-aca3a7ebed71330bc9403ee2806a5fca-1527259168/wordpress/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php (668)
in WP_REST_Posts_Controller::update_item called at ? (?)
in call_user_func called at /srv/www/release-aca3a7ebed71330bc9403ee2806a5fca-1527259168/wp-content/client-mu-plugins/hm-shared-media-library/inc/namespace.php (155)
in HumanMade\SharedMedia\rest_dispatch_requests called at /srv/www/release-aca3a7ebed71330bc9403ee2806a5fca-1527259168/wordpress/wp-includes/class-wp-hook.php (288)
in WP_Hook::apply_filters called at /srv/www/release-aca3a7ebed71330bc9403ee2806a5fca-1527259168/wordpress/wp-includes/plugin.php (203)
in apply_filters called at /srv/www/release-aca3a7ebed71330bc9403ee2806a5fca-1527259168/wordpress/wp-includes/rest-api/class-wp-rest-server.php (930)
in WP_REST_Server::dispatch called at /srv/www/release-aca3a7ebed71330bc9403ee2806a5fca-1527259168/wordpress/wp-includes/rest-api/class-wp-rest-server.php (321)
in WP_REST_Server::serve_request called at /srv/www/release-aca3a7ebed71330bc9403ee2806a5fca-1527259168/wordpress/wp-includes/rest-api.php (266)
in rest_api_loaded called at /srv/www/release-aca3a7ebed71330bc9403ee2806a5fca-1527259168/wordpress/wp-includes/class-wp-hook.php (286)
in WP_Hook::apply_filters called at /srv/www/release-aca3a7ebed71330bc9403ee2806a5fca-1527259168/wordpress/wp-includes/class-wp-hook.php (310)
in WP_Hook::do_action called at /srv/www/release-aca3a7ebed71330bc9403ee2806a5fca-1527259168/wordpress/wp-includes/plugin.php (515)
in do_action_ref_array called at /srv/www/release-aca3a7ebed71330bc9403ee2806a5fca-1527259168/wordpress/wp-includes/class-wp.php (373)
in WP::parse_request called at /srv/www/release-aca3a7ebed71330bc9403ee2806a5fca-1527259168/wordpress/wp-includes/class-wp.php (713)
in WP::main called at /srv/www/release-aca3a7ebed71330bc9403ee2806a5fca-1527259168/wordpress/wp-includes/functions.php (960)
```

 - https://rpm.newrelic.com/accounts/54748/applications/99514097/filterable_errors#/show/af5adbff-6034-11e8-a4bd-0242ac110008_8267_12295/stack_trace?top_facet=transactionUiName&primary_facet=error.class&barchart=barchart
 - https://rpm.newrelic.com/accounts/54748/applications/99514097/filterable_errors#/show/616768e7-602f-11e8-a4bd-0242ac110008_5038_9066/stack_trace?top_facet=transactionUiName&primary_facet=error.class&barchart=barchart
 - https://rpm.newrelic.com/accounts/54748/applications/99514097/filterable_errors#/show/3c6cf620-604a-11e8-a4bd-0242ac110008_2641_6065/stack_trace?top_facet=transactionUiName&primary_facet=error.class&barchart=barchart

**Comment by nathanielks** [comment]
@joehoyle 	curious where this is at on your priority list?

**Comment by electrokat** [comment]
Here's another one that was reported for Yell https://github.com/humanmade/Yell/issues/1309

**Comment by ntwb** [comment]
Another instance linked above in a client private repo

**Comment by markhughes** [comment]
@joehoyle maybe take some inspiration from this library how they split up the segments in this loop?

https://github.com/patrickkerrigan/php-xray/blob/master/src/Submission/DaemonSegmentSubmitter.php#L58

**Comment by joehoyle** [comment]
@markhughes thanks for the link! As it happens I now fixed this, in a somewhat similar way. The only current limitation we have is if a single segment is > 64kb, which I think is not solvable. This can happen if you have _many_ errors on a single segment for example.

I'm going to create a ticket to investigate using `php-xray` as a dependency of this project, hanks for point me to it!

**Comment by joehoyle** [comment]
As mentioned above, this is fixed in the latest version.
