### ISSUE TITLE
Apparently failed to update packagist

### ISSUE THREAD

**Issue by joehoyle** [humanmade/aws-xray#35]
The humanmade/aws-xray package of which you are a maintainer has
failed to update due to invalid data contained in your composer.json.
Please address this as soon as possible since the package stopped updating.

It is recommended that you use `composer validate` to check for errors when you
change your composer.json.

Below is the full update log which should highlight errors as
"Skipped branch ...":

[Composer\Repository\InvalidRepositoryException]: Some branches contained invalid data and were discarded, it is advised to review the log and fix any issues present in branches

Reading composer.json of humanmade/aws-xray (1.1.3)
Found cached composer.json of humanmade/aws-xray (1.1.3)
Reading composer.json of humanmade/aws-xray (1.1.2)
Found cached composer.json of humanmade/aws-xray (1.1.2)
Reading composer.json of humanmade/aws-xray (add-trace-id)
Skipped dev-add-trace-id, no composer file (cached from ref 5ca96c1f93ad95e05bdfcc96ac07a5f79dbd1a54)
Reading composer.json of humanmade/aws-xray (excimer)
Found cached composer.json of humanmade/aws-xray (dev-excimer)
Reading composer.json of humanmade/aws-xray (master)
Importing branch master (dev-master)
Skipped branch master, Invalid package information: 
License "GPL-v2.0+" is not a valid SPDX license identifier, see https://spdx.org/licenses/ if you use an open license.
If the software is closed-source, you may use "proprietary" as license.

Reading composer.json of humanmade/aws-xray (other-error-handlers)
Skipped dev-other-error-handlers, no composer file (cached from ref 19830fbd7be245113b42057a103825a04f9cb029)
Reading composer.json of humanmade/aws-xray (track-stats)
Found cached composer.json of humanmade/aws-xray (dev-track-stats)

**Comment by roborourke** [comment]
This was fixed in https://github.com/humanmade/aws-xray/pull/38
