### ISSUE TITLE
ReferenceError: jQuery is not defined flamegraph.js:622:1

### ISSUE THREAD

**Issue by ntwb** [humanmade/aws-xray#46]
Have just observed this error on a private HM client site:

```
ReferenceError: jQuery is not defined flamegraph.js:622:1
    <anonymous> https://example.com/content/hm-platform/plugins/aws-xray/assets/flamegraph.js?ver=2019-11-13:622
```

<img width="669" alt="image" src="https://user-images.githubusercontent.com/1016458/71653284-bf315800-2d7f-11ea-8e4d-3a3486f1758c.png">

**Comment by rmccue** [comment]
Should be fixed as of #43.
