### ISSUE TITLE
Track time spend in memcached / redis

### ISSUE THREAD

**Issue by joehoyle** [humanmade/aws-xray#5]
We should put this somewhere, the most _ideal_ xray way to do this is like a remote DB, where you track each call to the remote, and then you get the service graph with the remote / request per second, and error rate etc - however doing that for every memcached remote call might be overkill...

**Comment by veselala** [comment]
Moved this as a New idea to ProductBoard - https://altis.productboard.com/feature-board/2242997-product-features/features/16460597/detail
