### ISSUE TITLE
XHProf segment can be half the size

### ISSUE THREAD

**Issue by joehoyle** [humanmade/aws-xray#58]
In some cases, the XHProf segment seems to be half the length it should be. Not clear why, might be something to do with the re-segmenting to match a max segment size:

![](https://joehoyle-captured.s3.amazonaws.com/Screen-Shot-2020-03-04-10-12-43.03-FAA3TWjYu5BNMddc61EY6Ue94nRhpQZEBLXv3w91djgwJvQ70x0mMO4RfNALEVd6V1kbmshJpT0JWFx1bM8EIaz2jceblSyH9vmE.png)

**Comment by Nikschavan** [comment]
Probably fixed after https://github.com/humanmade/aws-xray/pull/63?

**Comment by joehoyle** [comment]
Ahyes, this has now been fixed!
