### ISSUE TITLE
Memory profiling in X-Ray

### ISSUE THREAD

**Issue by Nikschavan** [humanmade/aws-xray#71]
It would be very helpful if we were able to track the total memory for the trace and memory usage and % of the total memory for individual segments to help memory profiling.

This will probably need memory usage stats to be available from Xhprof. Tideways's Xhprof fork does add this memory functionality, just for a reference - https://github.com/tideways/php-xhprof-extension/pull/52

**Comment by rmccue** [comment]
We can definitely record peak memory usage as part of the request's attributes, but unlikely we'll be able to get it per segment. The Tideways change doesn't apply to sampling mode, only profiling mode (Tideways IIRC removed sampling mode altogether), so likely not useful here. We can't really run profiling mode on every request as it has overhead to running it.

Having the peak memory usage would at least allow you to spot potential problematic traces based on peak memory usage, and then dive in locally with either XDebug or Xhprof in profiling mode.

(nb, this may need to be paired with #8 for the specific issue you mention)

**Comment by Nikschavan** [comment]
We can get memory usage using `memory_get_usage()`, this can be added to [get_end_trace()](https://github.com/humanmade/aws-xray/blob/a151ce4ef40f4ba763fd40c668a5f4530fef0091/inc/namespace.php#L359).

This can be sent to X-Ray as [annotations](https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html#xray-concepts-annotations) in the end trace so that we will be able to use the filter expressions when searching for the traces, eg - `annotation.memoryUsage > 30`

I can work on a PR for this, Let me know if you have any suggestions on above @rmccue

**Comment by rmccue** [comment]
Sounds good to me, although I think you'll want `memory_get_peak_usage()`, as the memory may be clearing out by the time end trace is called; @joehoyle any concerns about this approach?

**Comment by Nikschavan** [comment]
Created a PR #76 with the first pass at this, based on the discussions above.

**Comment by joehoyle** [comment]
Could also be another future reason to switch to [Excimer](https://www.mediawiki.org/wiki/Excimer#Use_a_periodic_timer_to_gather_time-series_memory_usage_statistics). For now though I think this is good.

**Comment by joehoyle** [comment]
Released in https://github.com/humanmade/aws-xray/releases/tag/1.2.12
