### ISSUE TITLE
enable plugin on bedrock wpackagist

### ISSUE THREAD

**Issue by superali** [humanmade/aws-xray#84]
i need plugin to be installed on wordpress plugin folder 
now its getting installed on vendor folder
can you add support to bedrock deployment please

**Comment by rmccue** [comment]
Please note that we do not provide end-user support for this plugin, see our support policy: https://engineering.hmn.md/projects/support/

We'd be happy to consider pull requests that improve compatibility, however we do not intend on making any changes ourselves for this as we don't use Bedrock.
