### ISSUE TITLE
Sample interval is incorrect in case of Excimer

### ISSUE THREAD

**Issue by joehoyle** [humanmade/aws-xray#86]
We currently set the interval to 50ms in https://github.com/humanmade/aws-xray/blob/master/inc/namespace.php#L14, but we are setting xhprof to 5MS in https://github.com/humanmade/aws-xray/blob/master/inc/namespace.php#L37. I think we should have it at 5MS to reflect the old behavior. 

**Acceptance Criteria**

- [x] Profiles taken with Excimer should be at a 5MS interval
- [x] Do before and after performance analysis

**Comment by ferschubert-hm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Vulcan-6284e0dfb386b00c83981426/issues/humanmade/aws-xray/86?planning-poker) with Zenhub @jerico @kovshenin @mikelittle @wisyhambolu @sivanovhm

**Comment by veselala** [comment]
@jerico we've estimated this one to 3 SP and moved it to the Backlog.

**Comment by jerico** [comment]
@joehoyle How should we do performance analysis on this? What should we look for?

**Comment by joehoyle** [comment]
@jerico are you talking about measuring what the performance impact of switching to a 5ms interval over 50ms is? Or are you saying how should you verify the change from 5->50ms?

**Comment by jerico** [comment]
@joehoyle The acceptance criteria isn't clear about it. My assumption was the performance impact of switching to 5ms from 50ms. If this is it, I'm not sure how to do this and need guidance.

If it's the latter, I think I should be able to figure out how to verify the change.

**Comment by joehoyle** [comment]
Ohh yeah sorry I just noticed that!

If you make sure Xray is "working", i.e. check the Flamegraph in Altis Dev Tools, etc. You could probably do something like:

```
siege -c 1 -r 500 http://example.com/ --no-parser -H 'Cookie:wp_test=1'
```

Against your local site URL, and compare a before / after run. That is just saying "run 1 request at a time, for 500 requests, send a wp_test=1 cookie", which will make sure that the cache is busted each request.

**Comment by rmccue** [comment]
Remaining is the before/after performance analysis, keeping as 3.
